baseURL = "https://vca.epfl.ch"
languageCode = "en-us"
title = "VCA: Verification and Computer Architecture"
theme="archie"
copyright = "VCA Lab, EPFL"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="light"
useCDN=false

[taxonomies]
topic = "topics"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vca-epfl"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "People"
url = "/people"
weight = 2

[[menu.main]]
name = "Wiki"
url = "/wiki"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

[[menu.main]]
name = "Apply!"
url = "https://www.epfl.ch/education/phd/edic-computer-and-communication-sciences/edic-computer-and-communication-sciences/edic-how-to-apply/"
weight = 5
